# Generated by Django 4.2.6 on 2023-11-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "university_checker_app",
            "0002_university_delete_southafricapublicuniversity",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university_name", models.CharField(max_length=100)),
                ("sentiment_output", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tweets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university_name", models.CharField(max_length=100)),
                ("tweet_text", models.TextField()),
                ("sentiment_score", models.CharField(max_length=100)),
                ("created_at", models.TextField()),
            ],
        ),
    ]
