# Generated by Django 4.2.6 on 2023-11-04 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("university_checker_app", "0003_sentimentresult_tweets"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentResultAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentiment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university_checker_app.university",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SentimentResult",
        ),
    ]
