# Generated by Django 4.2.6 on 2023-11-04 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "university_checker_app",
            "0004_sentimentresultanalysis_delete_sentimentresult",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweets",
            name="university_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="university_checker_app.university",
            ),
        ),
    ]
