# Generated by Django 4.2.6 on 2023-11-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university_checker_app", "0005_alter_tweets_university_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweets",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
