# Generated by Django 4.2.6 on 2023-11-06 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("university_checker_app", "0006_alter_tweets_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tweets",
        ),
    ]
