# Generated by Django 4.2.6 on 2023-11-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university_checker_app", "0008_tweets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweets",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
