# Generated by Django 4.2.7 on 2023-11-08 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("university_checker_app", "0013_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
