# Generated by Django 4.2.7 on 2023-11-08 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("university_checker_app", "0015_alter_filteredtweets_negative_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FilteredTweets",
        ),
    ]
