# Generated by Django 4.2.7 on 2023-11-10 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("university_checker_app", "0017_filteredtweets"),
    ]

    operations = [
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("positive", models.TextField()),
                ("negative", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university_checker_app.university",
                    ),
                ),
            ],
        ),
    ]
