# Generated by Django 4.2.7 on 2023-11-10 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("university_checker_app", "0018_project"),
    ]

    operations = [
        migrations.DeleteModel(
            name="project",
        ),
    ]
